version: '3.7'
services:
  ciclozero_prod:
    image: butlerhat/ciclozero_prod:latest
    container_name: ciclozero_prod
    user: vscode
    init: true
    volumes:
      - ${HOST_HOME}/.cloudflared:/home/vscode/.cloudflared:cached
      - ${HOST_HOME}/data/CicloZero/results:/workspaces/CicloZero/results:cached
      - ${HOST_HOME}/data/CicloZero/downloads:/workspaces/CicloZero/downloads:cached
      - ${HOST_HOME}/data/CicloZero/data:/workspaces/CicloZero/data:cached
    cap_add:
      - SYS_ADMIN
    shm_size: '2gb'
    networks:
      - external
    environment:
      - ROBOT_CICLOZERO_PASS=${ROBOT_CICLOZERO_PASS:-0}
      - DEVELOPMENT_SERVER=${DEVELOPMENT_SERVER:-0}
    command: bash .devcontainer/postCreateCommand.sh

networks:
  external:
    name: net_robot
