version: '3.7'
services:
  ciclozero_prod:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
        GITHUB_TOKEN: ${GITHUB_TOKEN}
      target: prod
    container_name: ciclozero_prod
    user: vscode
    volumes:
      - ${HOST_HOME}/.cloudflared:/home/vscode/.cloudflared:cached
    cap_add:
      - SYS_ADMIN
    shm_size: '2gb'
    networks:
      - external
    environment:
      - ROBOT_CICLOZERO_PASS=${ROBOT_CICLOZERO_PASS:-0}
      - DEVELOPMENT_SERVER=${DEVELOPMENT_SERVER:-0}
    command: /bin/sh -c "while sleep 1000; do :; done"

networks:
  external:
    name: net_robot