version: '3.7'
services:
  ciclozero_prod:
    image: butlerhat/ciclozero_prod:latest
    container_name: ciclozero_prod
    user: vscode
    volumes:
      - ${HOST_HOME}/.cloudflared:/home/vscode/.cloudflared:cached
    cap_add:
      - SYS_ADMIN
    shm_size: '2gb'
    networks:
      - external
    environment:
      - ROBOT_CICLOZERO_PASS=${ROBOT_CICLOZERO_PASS:-0}
      - DEVELOPMENT_SERVER=${DEVELOPMENT_SERVER:-0}
    command: bash .devcontainer/postCreateCommand.sh

networks:
  external:
    name: net_robot
