version: '3.7'
services:
  ciclozero_dev:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
        GITHUB_TOKEN: ${GITHUB_TOKEN}
      target: base
    container_name: ciclozero
    init: true
    user: vscode
    volumes:
      - ..:/workspaces/CicloZero:cached
      - ${HOME}/.ssh:/home/vscode/.ssh:cached
      - ${HOME}/.cloudflared:/home/vscode/.cloudflared:cached
      - ${HOME}/data/CicloZero/results:/workspaces/CicloZero/results:cached
      - ${HOME}/data/CicloZero/downloads:/workspaces/CicloZero/downloads:cached
      - ${HOME}/data/CicloZero/data:/workspaces/CicloZero/data:cached
    cap_add:
      - SYS_ADMIN
    shm_size: '2gb'
    networks:
      - external
    environment:
      - ROBOT_CICLOZERO_PASS=${ROBOT_CICLOZERO_PASS:-0}
      - DEVELOPMENT_SERVER=${DEVELOPMENT_SERVER:-0}
    command: /bin/sh -c "while sleep 1000; do :; done"

networks:
  external:
    name: net_robot