version: '3.7'
services:
  ciclozero_dev:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
        GITHUB_TOKEN: ${GITHUB_TOKEN}
      target: base
    container_name: ciclozero_dev
    init: true
    user: vscode
    volumes:
      - ${HOME}/urjc_chapo/ai-butlerhat:/workspaces/ai-butlerhat:cached
      - ${HOME}/.ssh:/home/vscode/.ssh:cached
      - ${HOME}/data/CicloZero/results:/workspaces/ai-butlerhat/data-butlerhat/robotframework-butlerhat/TestSuites/CicloZero/prod_results:cached
      - ${HOME}/data/CicloZero/downloads:/workspaces/ai-butlerhat/data-butlerhat/robotframework-butlerhat/TestSuites/CicloZero/prod_downloads:cached
      - ${HOME}/data/CicloZero/data:/workspaces/ai-butlerhat/data-butlerhat/robotframework-butlerhat/TestSuites/CicloZero/data:cached
    cap_add:
      - SYS_ADMIN
    shm_size: '2gb'
    networks:
      - external
    environment:
      - ROBOT_CICLOZERO_PASS=${ROBOT_CICLOZERO_PASS:-0}
      - DEVELOPMENT_SERVER=${DEVELOPMENT_SERVER:-0}
      - EBAY_CLIENT_ID=${EBAY_CLIENT_ID:-0}
      - EBAY_CLIENT_SECRET=${EBAY_CLIENT_SECRET:-0}
      - EBAY_REFRESH_TOKEN=${EBAY_REFRESH_TOKEN:-0}
      - EBAY_REDIRECT_URI=${EBAY_REDIRECT_URI:-0}
      - EBAY_AUTHORIZATION_CODE=${EBAY_AUTHORIZATION_CODE:-0}
    command: /bin/sh -c "while sleep 1000; do :; done"

networks:
  external:
    name: net_robot