[paths]

logo = "./static/logo.png"
powered_by = "./static/powered_by.png"
ciclozero_logo = "./static/ciclozero_logo.png"
ciclozero_logo_old = "./static/ciclozero_logo_old.png"
robot = "/workspaces/ai-butlerhat/data-butlerhat/robotframework-butlerhat/TestSuites/CicloZero"
stock_excel = "/workspaces/ai-butlerhat/data-butlerhat/robotframework-butlerhat/TestSuites/CicloZero/downloads/stock"
price_excel = "/workspaces/ai-butlerhat/data-butlerhat/robotframework-butlerhat/TestSuites/CicloZero/downloads/price"
orders_linux = "./static/orders/orders_linux.zip"
orders_windows = "./static/orders/orders_windows.zip"
ebay_credentials = "/workspaces/ai-butlerhat/data-butlerhat/robotframework-butlerhat/TestSuites/CicloZero/web/.streamlit/ebay_credentials.yaml"

[ebay]
url_access_token = "https://api.sandbox.ebay.com/identity/v1/oauth2/token"
url_authorization_token = "https://auth.sandbox.ebay.com/oauth2/authorize"
url_identity_user = "https://apiz.sandbox.ebay.com/commerce/identity/v1/user/"


[configs]
auth_config = "./.streamlit/auth.yml"

[urls]
ocr = "http://nginx:80"

[theme]
base="dark"
primaryColor="#7D7D7D"
backgroundColor="#111111"
secondaryBackgroundColor="#3f4a65"

[browser]
gatherUsageStats = false