[paths]

logo = "./static/logo.png"
powered_by = "./static/powered_by.png"
ciclozero_logo = "./static/ciclozero_logo.png"
ciclozero_logo_old = "./static/ciclozero_logo_old.png"
robot = "/workspaces/ai-butlerhat/data-butlerhat/robotframework-butlerhat/TestSuites/CicloZero"
woocommerce_files = "/workspaces/ai-butlerhat/data-butlerhat/robotframework-butlerhat/TestSuites/CicloZero/robotframework/keywords/woocommerce_files"
stock_excel = "/workspaces/ai-butlerhat/data-butlerhat/robotframework-butlerhat/TestSuites/CicloZero/downloads/stock"
price_excel = "/workspaces/ai-butlerhat/data-butlerhat/robotframework-butlerhat/TestSuites/CicloZero/downloads/price"
orders_linux = "./static/orders/orders_linux.zip"
orders_windows = "./static/orders/orders_windows.zip"
extension = "./static/ebay_credentials_extension/chrome_plugin_cookies.zip"
cookies_dir = "/workspaces/ai-butlerhat/data-butlerhat/robotframework-butlerhat/TestSuites/CicloZero/browser/user_data_dir"
state_json = "/workspaces/ai-butlerhat/data-butlerhat/robotframework-butlerhat/TestSuites/CicloZero/browser/state/cookies.json"

[configs]
auth_config = "./.streamlit/auth.yml"

[urls]
ocr = "http://nginx:80"

[theme]
base="dark"
primaryColor="#7D7D7D"
backgroundColor="#111111"
secondaryBackgroundColor="#3f4a65"

[browser]
gatherUsageStats = false